# Non-sensitive information, but the value varies
# depending on whether or not you deploy via docker
dbHost: "DB_HOST"

# Sensitive information stored in env variables
dbUser: "DB_USER"
dbPassword: "DB_PASS"

# Non-sensitive information
dbName: "hippo_db"
dbPort: 3306
serverHost: "127.0.0.1"
serverPort: 3000
serverVersion: "0.0"


